# Geothermal stuff
GEOTHERMAL_NAMEPLATE_MW = 77
GEOTHERMAL_CAPACITY_KW = GEOTHERMAL_NAMEPLATE_MW * 1000
GEOTHERMAL_CAPACITY_FACTOR = 0.95
GEOTHERMAL_MIN_GENERATION = 0.1 * GEOTHERMAL_CAPACITY_KW
# We assume a ramp rate of 5% of nameplate capacity per minute
GEOTHERMAL_RAMP_RATE_PCT_PER_MINUTE = 0.05 
# Convert the ramp rate to an allowable step in kW for a 5-minute step size in t
MAX_GEOTHERMAL_STEP = GEOTHERMAL_RAMP_RATE_PCT_PER_MINUTE * GEOTHERMAL_CAPACITY_KW * 5 